# This is a basic workflow to help you get started with Actions

name: Mascota Merge Builder

on:
    push:
        branches: [ develop, main ]

defaults:
    run:
        shell: bash
        working-directory: .

jobs:
    build:
        name: Generate APK
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Gradle cache
                uses: actions/cache@v2
                with:
                    path: |
                        ~/.gradle/caches
                        ~/.gradle/wrapper
                    key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
                    restore-keys: |
                        ${{ runner.os }}-gradle-
            -   name: set up JDK 1.8
                uses: actions/setup-java@v1
                with:
                    java-version: 1.8

            -   name: Change gradlew permissions
                run: chmod +x ./gradlew

            -   name: Build debug APK
                run: ./gradlew assembleDebug --stacktrace

    

            -   name: Upload APK
                if: ${{ success() }}
                uses: MeilCli/slack-upload-file@v1
                with:
                    slack_token: ${{ secrets.SLACK_READ_WRITE_TOKEN }}
                    channels: ${{ secrets.SLACK_CHANNEL_DEPOLY }}
                    file_path: 'app/build/outputs/apk/debug/app-debug.apk'
                    file_name: 'SobokSobok.apk'
                    file_type: 'apk'
                    initial_comment: '소복소복 APK'
